---
deployment:
  tasks:
    - export NODE_ENV=production
    - 'export PATH="$HOME/nodevenv/clean_heights_app/22/bin:$PATH"'
    - npm run build
    - 'test -f dist/index.js && test -f dist/public/index.html'
